version: '3.8'

services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: media-vault-backend/Dockerfile
    environment:
      - DB_HOST=test-db
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - DB_NAME=test_db
      - REDIS_HOST=test-redis
    depends_on:
      test-db:
        condition: service_healthy
      test-redis:
        condition: service_healthy
    volumes:
      - ./media-vault-backend:/app
    command: >
      sh -c "go test -v ./... -coverprofile=coverage.out && \
             go tool cover -html=coverage.out -o coverage.html"
