groups:
  - name: media-vault-critical
    rules:
      # Critical Infrastructure Alerts
      - alert: ServiceCompletleyDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "Service {{ $labels.job }} is completely down"
          description: "{{ $labels.job }} has been down for more than 1 minute"
          runbook_url: "https://wiki.mediavault.com/runbooks/service-down"
          action: "Immediate investigation required"

      - alert: DiskWillFillIn4Hours
        expr: predict_linear(node_filesystem_avail_bytes{mountpoint="/"}[1h], 4*3600) < 0
        for: 5m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "Disk will fill up in 4 hours"
          description: "Disk space will be exhausted in approximately 4 hours"
          action: "Clean up space or expand storage immediately"

      - alert: DatabaseConnectionExhaustion
        expr: sum(pg_stat_activity_count) > 80
        for: 2m
        labels:
          severity: critical
          team: database
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "PostgreSQL has {{ $value }} active connections (limit ~100)"
          action: "Check for connection leaks or scale database"

      # Security Alerts
      - alert: SuspiciousLoginActivity
        expr: increase(keycloak_failed_login_attempts[5m]) > 20
        for: 1m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "Unusual login activity detected"
          description: "{{ $value }} failed login attempts in 5 minutes"
          action: "Check for brute force attacks, consider IP blocking"

      - alert: UnauthorizedAPIAccess
        expr: increase(http_requests_total{code=~"401|403"}[5m]) > 50
        for: 2m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "High number of unauthorized API requests"
          description: "{{ $value }} unauthorized requests in 5 minutes"
          action: "Investigate potential security breach"

  - name: media-vault-performance
    rules:
      # Performance Degradation
      - alert: APIResponseTimeDegraded
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "API response time degraded"
          description: "95th percentile response time is {{ $value }}s"
          action: "Investigate performance bottlenecks"

      - alert: HighMemoryPressure
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 10m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High memory pressure detected"
          description: "Memory usage is {{ $value | humanizePercentage }}"
          action: "Consider scaling or optimizing memory usage"

      - alert: SwapUsageHigh
        expr: (node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes > 0.5
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High swap usage detected"
          description: "Swap usage is {{ $value | humanizePercentage }}"
          action: "Investigate memory pressure and optimize"

      # Network Issues
      - alert: HighNetworkErrors
        expr: rate(node_network_receive_errs_total[5m]) + rate(node_network_transmit_errs_total[5m]) > 10
        for: 3m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High network error rate"
          description: "Network errors: {{ $value }} errors/second"
          action: "Check network configuration and hardware"

  - name: media-vault-business
    rules:
      # Business Logic Alerts
      - alert: UploadFailureRateHigh
        expr: (rate(vault_upload_failures_total[5m]) / rate(vault_upload_attempts_total[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
          team: application
        annotations:
          summary: "High upload failure rate"
          description: "{{ $value | humanizePercentage }} of uploads are failing"
          action: "Check storage capacity and upload service health"

      - alert: NSFWDetectionServiceDown
        expr: up{job="nsfw-analyzer"} == 0
        for: 1m
        labels:
          severity: warning
          team: ml
        annotations:
          summary: "NSFW detection service is down"
          description: "Content moderation is not functioning"
          action: "Restart NSFW analyzer service"

      - alert: VaultStorageUtilizationHigh
        expr: (vault_storage_used_bytes / vault_storage_total_bytes) > 0.85
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "Vault storage utilization high"
          description: "Storage is {{ $value | humanizePercentage }} full"
          action: "Plan storage expansion or implement cleanup policies"

